#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-maven-deploy-plugin
Version  : 2.8.2
Release  : 1
URL      : https://github.com/apache/maven-deploy-plugin/archive/maven-deploy-plugin-2.8.2.tar.gz
Source0  : https://github.com/apache/maven-deploy-plugin/archive/maven-deploy-plugin-2.8.2.tar.gz
Source1  : https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-deploy-plugin/2.8.2/maven-deploy-plugin-2.8.2.jar
Source2  : https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-deploy-plugin/2.8.2/maven-deploy-plugin-2.8.2.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0

%description
No detailed description available

%prep

%build

%install

%files
%defattr(-,root,root,-)
